component_depth: 1
languages:
- java
exclude:
- ./Info/.*
- ./bin/.*
- ./bin/ant/.*
- ./bin/meta-inf/.*
- ./bin/net/.*
- ./bin/org/.*
- ./bin/org/acm/.*
- ./bin/org/acm/seguin/.*
- ./bin/org/acm/seguin/ant/.*
- ./bin/org/acm/seguin/awt/.*
- ./bin/org/acm/seguin/findbugs/.*
- ./bin/org/acm/seguin/ide/.*
- ./bin/org/acm/seguin/ide/cafe/.*
- ./bin/org/acm/seguin/ide/command/.*
- ./bin/org/acm/seguin/ide/common/.*
- ./bin/org/acm/seguin/ide/common/action/.*
- ./bin/org/acm/seguin/ide/common/icons/.*
- ./bin/org/acm/seguin/ide/common/options/.*
- ./bin/org/acm/seguin/ide/elixir/.*
- ./bin/org/acm/seguin/ide/elixir/version/.*
- ./bin/org/acm/seguin/ide/jbuilder/.*
- ./bin/org/acm/seguin/ide/jbuilder/refactor/.*
- ./bin/org/acm/seguin/ide/jdeveloper/.*
- ./bin/org/acm/seguin/ide/jedit/.*
- ./bin/org/acm/seguin/ide/jedit/action/.*
- ./bin/org/acm/seguin/ide/jedit/event/.*
- ./bin/org/acm/seguin/ide/jooda/.*
- ./bin/org/acm/seguin/ide/kawa/.*
- ./bin/org/acm/seguin/ide/netbeans/.*
- ./bin/org/acm/seguin/ide/standalone/.*
- ./bin/org/acm/seguin/io/.*
- ./bin/org/acm/seguin/junit/.*
- ./bin/org/acm/seguin/metrics/.*
- ./bin/org/acm/seguin/pmd/.*
- ./bin/org/acm/seguin/pmd/ant/.*
- ./bin/org/acm/seguin/pmd/cpd/.*
- ./bin/org/acm/seguin/pmd/cpd/cppast/.*
- ./bin/org/acm/seguin/pmd/jaxen/.*
- ./bin/org/acm/seguin/pmd/renderers/.*
- ./bin/org/acm/seguin/pmd/rules/.*
- ./bin/org/acm/seguin/pmd/rules/design/.*
- ./bin/org/acm/seguin/pmd/rules/junit/.*
- ./bin/org/acm/seguin/pmd/rules/strictexception/.*
- ./bin/org/acm/seguin/pmd/stat/.*
- ./bin/org/acm/seguin/pmd/swingui/.*
- ./bin/org/acm/seguin/pmd/swingui/event/.*
- ./bin/org/acm/seguin/pmd/swingui/icons/.*
- ./bin/org/acm/seguin/pmd/symboltable/.*
- ./bin/org/acm/seguin/pmd/util/.*
- ./bin/org/acm/seguin/pretty/.*
- ./bin/org/acm/seguin/pretty/ai/.*
- ./bin/org/acm/seguin/pretty/jdi/.*
- ./bin/org/acm/seguin/pretty/line/.*
- ./bin/org/acm/seguin/pretty/sort/.*
- ./bin/org/acm/seguin/print/.*
- ./bin/org/acm/seguin/print/text/.*
- ./bin/org/acm/seguin/print/xml/.*
- ./bin/org/acm/seguin/project/.*
- ./bin/org/acm/seguin/refactor/.*
- ./bin/org/acm/seguin/refactor/field/.*
- ./bin/org/acm/seguin/refactor/method/.*
- ./bin/org/acm/seguin/refactor/type/.*
- ./bin/org/acm/seguin/refactor/undo/.*
- ./bin/org/acm/seguin/summary/.*
- ./bin/org/acm/seguin/summary/load/.*
- ./bin/org/acm/seguin/summary/query/.*
- ./bin/org/acm/seguin/tools/.*
- ./bin/org/acm/seguin/tools/build/.*
- ./bin/org/acm/seguin/tools/builder/.*
- ./bin/org/acm/seguin/tools/install/.*
- ./bin/org/acm/seguin/tools/international/.*
- ./bin/org/acm/seguin/tools/stub/.*
- ./bin/org/acm/seguin/uml/.*
- ./bin/org/acm/seguin/uml/jpg/.*
- ./bin/org/acm/seguin/uml/line/.*
- ./bin/org/acm/seguin/uml/loader/.*
- ./bin/org/acm/seguin/uml/print/.*
- ./bin/org/acm/seguin/uml/refactor/.*
- ./bin/org/acm/seguin/util/.*
- ./bin/org/acm/seguin/version/.*
- ./bin/org/apache/.*
- ./bin/org/apache/tools/.*
- ./bin/org/apache/tools/ant/.*
- ./bin/org/apache/tools/ant/taskdefs/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/.*
- ./bin/org/apache/tools/ant/taskdefs/optional/javastyle/.*
- ./bin/settings/.*
- ./bin/test/.*
- ./bin/test/net/.*
- ./bin/ui/.*
- ./build.dest/.*
- ./completer/.*
- ./completer/info/.*
- ./completer/popup/.*
- ./jEditFiles/.*
- ./jar/.*
- ./jar/dummy/.*
- ./javacc/.*
- ./javacc/ast/.*
- ./lib/.*
- ./lib/dummy/.*
- ./lib/modules/.*
- ./netbeans/.*
- ./netbeans/modules/.*
- ./rulesets/.*
- ./settings/.*
- ./test/.*
- ./test/check/.*
- ./test/check/lineno/.*
- ./test/check/pretty/.*
- ./test/check/pretty/JDK1_5/.*
- ./test/check/testextractinterface/.*
- ./test/check/ut1/.*
- ./test/check/ut1/step1/.*
- ./test/check/ut1/step10/.*
- ./test/check/ut1/step11/.*
- ./test/check/ut1/step12/.*
- ./test/check/ut1/step13/.*
- ./test/check/ut1/step14/.*
- ./test/check/ut1/step15/.*
- ./test/check/ut1/step16/.*
- ./test/check/ut1/step17/.*
- ./test/check/ut1/step18/.*
- ./test/check/ut1/step19/.*
- ./test/check/ut1/step2/.*
- ./test/check/ut1/step20/.*
- ./test/check/ut1/step21/.*
- ./test/check/ut1/step22/.*
- ./test/check/ut1/step23/.*
- ./test/check/ut1/step24/.*
- ./test/check/ut1/step25/.*
- ./test/check/ut1/step26/.*
- ./test/check/ut1/step3/.*
- ./test/check/ut1/step30/.*
- ./test/check/ut1/step4/.*
- ./test/check/ut1/step40/.*
- ./test/check/ut1/step5/.*
- ./test/check/ut1/step6/.*
- ./test/check/ut1/step7/.*
- ./test/check/ut1/step8/.*
- ./test/check/ut1/step9/.*
- ./test/check/ut2/.*
- ./test/check/ut2/step1/.*
- ./test/check/ut2/step11/.*
- ./test/check/ut2/step12/.*
- ./test/check/ut2/step13/.*
- ./test/check/ut2/step14/.*
- ./test/check/ut2/step15/.*
- ./test/check/ut2/step16/.*
- ./test/check/ut2/step2/.*
- ./test/check/ut2/step3/.*
- ./test/check/ut2/step4/.*
- ./test/check/ut2/step5/.*
- ./test/check/ut3/.*
- ./test/check/ut3/step1/.*
- ./test/check/ut3/step10/.*
- ./test/check/ut3/step11/.*
- ./test/check/ut3/step12/.*
- ./test/check/ut3/step13/.*
- ./test/check/ut3/step14/.*
- ./test/check/ut3/step15/.*
- ./test/check/ut3/step16/.*
- ./test/check/ut3/step2/.*
- ./test/check/ut3/step20/.*
- ./test/check/ut3/step21/.*
- ./test/check/ut3/step22/.*
- ./test/check/ut3/step23/.*
- ./test/check/ut3/step24/.*
- ./test/check/ut3/step25/.*
- ./test/check/ut3/step26/.*
- ./test/check/ut3/step27/.*
- ./test/check/ut3/step28/.*
- ./test/check/ut3/step29/.*
- ./test/check/ut3/step3/.*
- ./test/check/ut3/step30/.*
- ./test/check/ut3/step31/.*
- ./test/check/ut3/step32/.*
- ./test/check/ut3/step33/.*
- ./test/check/ut3/step34/.*
- ./test/check/ut3/step35/.*
- ./test/check/ut3/step36/.*
- ./test/check/ut3/step38/.*
- ./test/check/ut3/step39/.*
- ./test/check/ut3/step4/.*
- ./test/check/ut3/step40/.*
- ./test/check/ut3/step41/.*
- ./test/check/ut3/step42/.*
- ./test/check/ut3/step45/.*
- ./test/check/ut3/step46/.*
- ./test/check/ut3/step47/.*
- ./test/check/ut3/step5/.*
- ./test/check/ut3/step50/.*
- ./test/check/ut3/step51/.*
- ./test/check/ut3/step52/.*
- ./test/check/ut3/step53/.*
- ./test/check/ut3/step54/.*
- ./test/check/ut3/step55/.*
- ./test/check/ut3/step56/.*
- ./test/check/ut3/step57/.*
- ./test/check/ut3/step6/.*
- ./test/check/ut3/step7/.*
- ./test/check/ut4/.*
- ./test/check/ut4/step1/.*
- ./test/check/ut4/step2/.*
- ./test/check/ut4/step3/.*
- ./test/check/ut4/step4/.*
- ./test/clean/.*
- ./test/clean/pretty/.*
- ./test/clean/pretty/jdk1_5/.*
- ./test/clean/ren/.*
- ./test/clean/testextractinterface/.*
